version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - 3303:3306
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    networks:
      - site_rent
  client:
    build: ./client
    container_name: frontend-container
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - site_rent
  server:
    container_name: backend-container
    build: ./server
    ports:
      - 8000:8000
    environment:
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_NAME: my_db
      DB_USER: user
      DB_PASSWORD: userpassword
    depends_on:
      - mysql
    networks:
      - site_rent
networks:
  site_rent: